[package]
name = "atsamd21g18a"
version = "0.1.0"
edition = "2021"

[features]
rt = ["cortex-m-rt/device"]

[dependencies]
cortex-m = { version = "0.7" }
cortex-m-rt = { version = "0.7", optional = true }
vcell = { version = "0.1" }
