[package]
name = "ntcrackfpga_versaboard"
version = "0.1.0"
edition = "2021"

[features]
# Active when a crystal is installed on the board, not an oscillator.
crystal = []

[dependencies]
atsaml21g18b = { path = "../atsaml21g18b", features = ["rt"] }
cortex-m = { version = "0.7" }
