name: ntcrackfpga build
on: [push]
jobs:
  build-bitstream:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm git iverilog ninja
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/ntcrackfpga/ntcrackfpga
      - name: check out repository code
        uses: actions/checkout@v2
      - name: prepare oss-cad-suite directory
        run: mkdir -p /opt/oss-cad-suite/download
      - name: obtain latest oss-cad-suite binaries for linux-x64
        uses: i3h/download-release-asset@v1
        with:
          if: ${{ runner.arch == "X64" }}
          owner: YosysHQ
          repo: oss-cad-suite-build
          tag: latest
          file: "oss-cad-suite-linux-x64-.*[.]tgz"
          path: /opt/oss-cad-suite/download
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: obtain latest oss-cad-suite binaries for linux-arm64
        uses: i3h/download-release-asset@v1
        with:
          if: ${{ runner.arch == "ARM64" }}
          owner: YosysHQ
          repo: oss-cad-suite-build
          tag: latest
          file: "oss-cad-suite-linux-arm64-.*[.]tgz"
          path: /opt/oss-cad-suite/download
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: extract oss-cad-suite
        run: tar -C /opt -xvf /opt/oss-cad-suite/download/oss-cad-suite-linux-*.tgz
      - name: source environment file
        # yes, the space between dot and slash is intended
        run: . /opt/oss-cad-suite/environment
      - name: run build
        run: ninja build
      - name: upload bitstream
        uses: actions/upload-artifact@v2
        with:
          path: |
            ntcrackfpga.svf
            ntcrackfpga.bit
  build-driver:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm git rustup
      - name: install rust base installation
        run: rustup
      - name: include rust in environment
        run: . ~/.cargo/env
      - name: install rust toolchain for the Arduino Zero's microcontroller (SAMD21)
        run: rustup target add thumbv6m-none-eabi
      - name: install rust LLVM tools
        run: rustup component add llvm-tools-preview
      - name: install cargo-binutils
        run: cargo install binutils
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/ntcrackfpga/ntcrackfpga
      - name: check out repository code
        uses: actions/checkout@v2
      - name: switch directory
        run: cd driverboard
      - name: run build
        run: cargo build --release
      - name: convert ELF to raw binary
        run: rust-objcopy --output-target=binary target/thumbv6m-none-eabi/release/ntcrackfpga_driver target/thumbv6m-none-eabi/release/ntcrackfpga_driver.bin
      - name: upload binaries
        uses: actions/upload-artifact@v2
        with:
          path: |
            driverboard/target/thumbv6m-none-eabi/release/ntcrackfpga_driver
            driverboard/target/thumbv6m-none-eabi/release/ntcrackfpga_driver.bin
